feat: Add Sigstore verification capabitilies in PolicyServers CRD
kubewarden/kubewarden-controller pull request #139
Opened 2021-12-17 11:43 UTC by viccuad

- Add 2 new keys to PolicyServer spec:
  - `enableVerification`: Defaults to false, optional. If true,
   `verificationSecret` will be used.
  - `verificationSecret`: Name of k8s secret in the same ns that contains
    the verification configuration for the policy-server[1].

  If verification enabled, the secret would be mounted on the containers   of the policy-server, and it will be set to enable verification with  that configuration.

- Unit tests are covered by existing ones, as there's change of env in the container.
- A simple E2E idempotent test has been added, see `e2e-tests` directory.
  I'm happy dropping it, but it was easier to push that than to paste and explain the testing in the PR. They may need more setup and cleanup if more tests are added, but should be doable.
  
  I am on the opinion that these kind of tests should be part of the repo, as they are tightly coupled with the code that implements them (and aid review of features). A CI engine, living in a different repo, can be used as a dependency to run these kubewarden-controller e2e tests (and others, with more coverage of the full stack, for example chart behaviour tests, living in the chart repo). That way, we can check in the tests closer to the code, for easier refactoring and debugging of failing tests.
  
  
Fixes: https://github.com/kubewarden/kubewarden-controller/issues/137
Depends on https://github.com/kubewarden/policy-server/pull/132, so until that is merged, one needs to build a local policy-server image, inject it in cluster, and change `e2e-tests/test-verification/resources/server-with-verification.yml` to use it (plus change ImagePullPolicy to Never on the server deployment).

2021-12-20 07:48 UTC, flavio reviewed
Looks good to me, I just left one comment

2021-12-20 07:48 UTC, flavio commented on apis/policies/v1alpha2/policyserver_types.go
> +	// PolicyServerVerificationSecretReconciled PolicyConditionType = "PolicyServerVerificationSecretReconciled"
Are you sure this line should be commented? :thinking:

2021-12-21 14:35 UTC, flavio approved these changes
LGTM, but this needs to be rebased against main

2021-12-21 14:48 UTC, viccuad commented
Rebased onto main; I would still wait until the policy-server has the functionality, so one can run the e2e-tests on this PR manually.

2021-12-21 14:51 UTC, flavio commented
> Rebased onto main; I would still wait until the policy-server has the functionality, so one can run the e2e-tests on this PR manually.

Fine with me :+1:

2021-12-21 20:05 UTC, jvanz approved these changes

2022-01-12 08:23 UTC, flavio commented
> Rebased onto main; I would still wait until the policy-server has the functionality, so one can run the e2e-tests on this PR manually.

JFYI: the latest policy server from main has the sigstore integration enabled

2022-01-12 12:35 UTC, viccuad commented
Run the e2e-tests included here, and it works. Discovered https://github.com/kubewarden/policy-server/pull/141 though.

Still, I realized that we have bad UX:
We are using a secret for the `verification.yml` config. From what I can tell, there's no way to mount a generic secret under a filename, as it mounts keys inside the `data` of the secret instead. In our case, by how we create the secret in the tests using `--from-file`, we have a key `data.verification.yml`, as the filename for the secret is named `verification.yml`.

This is confusing, and users may not realize that they need to name their file `verification.yml` (nor they may want to).

I think verification.yml should come from a Configmap, which can then be mounted as a file.

2022-01-12 15:13 UTC, viccuad commented
I have redone the PR with a configmap for the verification config, instead of a secret. I have force-pushed changing the commit "feat: Add verification options to PolicyServer " incluse and onwards, sorry WRT to review (ended up with too many fixups, preferred to squash).

Tests passing locally.

Both Configmaps and Secrets can't be mounted as 1 file. Hence, when creating the configmap, one needs to specify that the key `verification-config` is the one that will be used. Example from the tests:
> kubectl create configmap my-verification-config \
   --from-file=**verification-config**=./resources/my-verification-config.yml \
   --namespace=kubewarden

2022-01-13 07:48 UTC, flavio approved these changes
LGTM

2022-01-13 15:42 UTC, viccuad commented
Force-pushed again, changing the last 2 commits, so the PolicyServer CRD only gains the new setting `verificationConfig`. Updated the e2e-tests example `server-with-verification.yml`.

Tests passing locally.

2022-01-14 16:45 UTC, flavio requested changes
I think there's one minor change to be done, then this is going to be good for merge

2022-01-17 12:04 UTC, viccuad commented on internal/pkg/admission/policy-server-deployment.go
> +		)
Done in https://github.com/kubewarden/kubewarden-controller/pull/139/commits/67c811182db60cf351783a0e979612b76c99d995!

2022-01-17 13:34 UTC, flavio approved these changes
LGTM

2022-01-18 07:59 UTC, merged