Use Webhook started checker in the readiness probe.
kubewarden/kubewarden-controller pull request #148
Opened 2022-01-21 20:27 UTC by jvanz

Updates the function used in the readiness probe. The function provided by the Webhook is used to ensure that the manager already start its runnables before start replying that the controller is ready.

2022-01-21 20:39 UTC, jvanz commented
@viccuad, as I could not simulate the issue, can you test this in your environment? I've pushed a container image with this change at ghcr.io/jvanz/kubewarden-controller:controller-readiness-probe

2022-01-22 06:48 UTC, flavio reviewed
Seems an easy fix :+1: 

Is there anything else we should check to ensure we're ready? Have you tested this fixes the corner case you found?

2022-01-24 11:21 UTC, jvanz commented
> Seems an easy fix +1
> 
> Is there anything else we should check to ensure we're ready? Have you tested this fixes the corner case you found?

I've ran the end-to-end tests. To ensure that all the basic operations are working.

2022-01-25 16:07 UTC, viccuad commented
I can't try with k3d, as it is not working for me on 2 different machines right now.

Tried with minikube:
```
$ minikube delete; minikube start
$ kubectl apply -f https://github.com/jetstack/cert-manager/releases/latest/download/cert-manager.yaml
$ kubectl wait --for=condition=Available deployment --timeout=2m -n cert-manager --all
$ helm install --wait -n kubewarden --create-namespace kubewarden-crds kubewarden/kubewarden-crds
$ helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller --set image.repository=ghcr.io/jvanz/kubewarden-controller --set image.tag=controller-readiness-probe
```

And I get:
```
Error: failed post-install: warning: Hook post-install kubewarden-controller/templates/policyserver-default.yaml failed: Internal error occurred: failed calling webhook "mpolicyserver.kb.io": failed to call webhook: Post "https://kubewarden-controller-webhook-service.kubewarden.svc:443/mutate-policies-kubewarden-io-v1alpha2-policyserver?timeout=10s": context deadline exceeded
```

Which looks like an error on the same webhook that the original bug talked about.

Could it be that the readyz check is waiting for the controller manager to be registered against the admission controller of Kubernetes, but it should be waiting for the controller manager to accept admission/mutating webhooks?

2022-01-26 15:26 UTC, ereslibre approved these changes
LGTM. I wonder if we could contribute this change to kubebuilder so it's the default when scaffolding. I wonder why this is not the default already...

2022-01-26 15:27 UTC, ereslibre commented
I must say I have not tried it.

2022-01-27 13:00 UTC, jvanz commented
> LGTM. I wonder if we could contribute this change to kubebuilder so it's the default when scaffolding. I wonder why this is not the default already...

I've filed an issue to discuss that. I'll try to implement that there. ;)

2022-01-27 18:39 UTC, jvanz commented
> Could it be that the readyz check is waiting for the controller manager to be registered against the admission controller of Kubernetes, but it should be waiting for the controller manager to accept admission/mutating webhooks?

I do not think so. The webhooks are [registered](https://github.com/kubewarden/kubewarden-controller/blob/main/main.go#L95-L108) before even the [start of the webhook server](https://github.com/kubewarden/kubewarden-controller/blob/main/main.go#L141). And the checker returns "Ready" when the [webhook server is started](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.10.0/pkg/webhook/server.go#L294-L318). 

@viccuad, do you have something in your env which can cause the server take more time to respond? Some resource constraints or something like that?

2022-02-01 10:23 UTC, viccuad commented
I don't have anything special hogging resources, and this is in my Thinkpad t14s, with the pasted commands before.

I trigger the installation of the controller chart. The `kubewarden-controller` pod appears, gets ready 1/1, then ~5 seconds pass, and I get the error:

```
$ helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller --set image.repository=ghcr.io/jvanz/kubewarden-controller --set image.tag=controller-readiness-probe
Error: failed post-install: warning: Hook post-install kubewarden-controller/templates/policyserver-default.yaml failed: Internal error occurred: failed calling webhook "mpolicyserver.kb.io": failed to call webhook: Post "https://kubewarden-controller-webhook-service.kubewarden.svc:443/mutate-policies-kubewarden-io-v1alpha2-policyserver?timeout=10s": dial tcp 10.97.118.138:443: i/o timeout
```

The controller logs show that helm didn't arrive to the post-install hook, hence, there's no policy-server-default CRD nor is it in the controller logs:

```logs
2022-02-01T10:19:13.536Z    INFO    controller-runtime.metrics    metrics server is starting to listen    {"addr": ":8088"}                                                                                                                                                                 
2022-02-01T10:19:13.537Z    INFO    controller-runtime.builder    Registering a mutating webhook    {"GVK": "policies.kubewarden.io/v1alpha2, Kind=PolicyServer", "path": "/mutate-policies-kubewarden-io-v1alpha2-policyserver"}                                                           
2022-02-01T10:19:13.537Z    INFO    controller-runtime.webhook    registering webhook    {"path": "/mutate-policies-kubewarden-io-v1alpha2-policyserver"}                                                                                                                                   
2022-02-01T10:19:13.537Z    INFO    controller-runtime.builder    skip registering a validating webhook, admission.Validator interface is not implemented    {"GVK": "policies.kubewarden.io/v1alpha2, Kind=PolicyServer"}                                                                  
2022-02-01T10:19:13.537Z    INFO    controller-runtime.builder    Registering a mutating webhook    {"GVK": "policies.kubewarden.io/v1alpha2, Kind=ClusterAdmissionPolicy", "path": "/mutate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy"}                                       
2022-02-01T10:19:13.538Z    INFO    controller-runtime.webhook    registering webhook    {"path": "/mutate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy"}                                                                                                                         
2022-02-01T10:19:13.538Z    INFO    controller-runtime.builder    Registering a validating webhook    {"GVK": "policies.kubewarden.io/v1alpha2, Kind=ClusterAdmissionPolicy", "path": "/validate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy"}                                   
2022-02-01T10:19:13.538Z    INFO    controller-runtime.webhook    registering webhook    {"path": "/validate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy"}                                                                                                                       
2022-02-01T10:19:13.538Z    INFO    setup    starting manager                                                                                                                                                                                                                               
I0201 10:19:13.539324       1 leaderelection.go:248] attempting to acquire leader lease kubewarden/a4ddbf36.kubewarden.io...                                                                                                                                                                
2022-02-01T10:19:13.539Z    INFO    controller-runtime.webhook.webhooks    starting webhook server                                                                                                                                                                                          
2022-02-01T10:19:13.540Z    INFO    controller-runtime.certwatcher    Updated current TLS certificate                                                                                                                                                                                       
2022-02-01T10:19:13.540Z    INFO    controller-runtime.webhook    serving webhook server    {"host": "", "port": 9443}                                                                                                                                                                      
2022-02-01T10:19:13.540Z    INFO    controller-runtime.certwatcher    Starting certificate watcher                                                                                                                                                                                          
I0201 10:19:13.556998       1 leaderelection.go:258] successfully acquired lease kubewarden/a4ddbf36.kubewarden.io                                                                                                                                                                          
2022-02-01T10:19:13.557Z    DEBUG    events    Normal    {"object": {"kind":"ConfigMap","namespace":"kubewarden","name":"a4ddbf36.kubewarden.io","uid":"ae8b58e5-dd4f-4cc2-b452-4e33f8feb83a","apiVersion":"v1","resourceVersion":"743"}, "reason": "LeaderElection", "message": "kubewarden
-controller-6bd7bcc669-2bp2n_b45976e3-7e23-4c8f-9da4-2131c7e7e9e7 became leader"}                                                                                                                                                                                                           
2022-02-01T10:19:13.557Z    DEBUG    events    Normal    {"object": {"kind":"Lease","namespace":"kubewarden","name":"a4ddbf36.kubewarden.io","uid":"64342291-262d-4286-b3c5-1095971ef9cb","apiVersion":"coordination.k8s.io/v1","resourceVersion":"744"}, "reason": "LeaderElection", "messa
ge": "kubewarden-controller-6bd7bcc669-2bp2n_b45976e3-7e23-4c8f-9da4-2131c7e7e9e7 became leader"}                                                                                                                                                                                           
2022-02-01T10:19:13.640Z    INFO    starting metrics server    {"path": "/metrics"}                                                                                                                                                                                                         
2022-02-01T10:19:13.640Z    INFO    controller.policyserver    Starting EventSource    {"reconciler group": "policies.kubewarden.io", "reconciler kind": "PolicyServer", "source": "kind source: /, Kind="}                                                                                 
2022-02-01T10:19:13.640Z    INFO    controller.policyserver    Starting EventSource    {"reconciler group": "policies.kubewarden.io", "reconciler kind": "PolicyServer", "source": "kind source: /, Kind="}                                                                                 
2022-02-01T10:19:13.640Z    INFO    controller.policyserver    Starting Controller    {"reconciler group": "policies.kubewarden.io", "reconciler kind": "PolicyServer"}                                                                                                                     
2022-02-01T10:19:13.640Z    INFO    controller.policyserver    Starting workers    {"reconciler group": "policies.kubewarden.io", "reconciler kind": "PolicyServer", "worker count": 1} 
```

2022-02-01 13:00 UTC, nunix commented
hi Team,

I'm currently facing the exact same issue with Rancher Desktop (on Windows):
```bash
# The CRDs chart installs without issue
helm install --wait -n kubewarden --create-namespace kubewarden-crds kubewarden/kubewarden-crds
NAME: kubewarden-crds
LAST DEPLOYED: Tue Feb  1 13:54:49 2022
NAMESPACE: kubewarden
STATUS: deployed
REVISION: 1
TEST SUITE: None

# The controller chart fails to install
helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller
Error: INSTALLATION FAILED: failed post-install: warning: Hook post-install kubewarden-controller/templates/policyserver-default.yaml failed: Internal error occurred: failed calling webhook "mpolicyserver.kb.io": failed to call webhook: Post "https://kubewarden-controller-webhook-service.kubewarden.svc:443/mutate-policies-kubewarden-io-v1alpha2-policyserver?timeout=10s": context deadline exceeded
```

I uninstalled the controller and tried to reinstall it with the image from @jvanz : 
```bash
# Uninstalled the controller
 helm uninstall --namespace kubewarden kubewarden-controller
release "kubewarden-controller" uninstalled

# Installed the controller with the new image
helm install --wait -n kubewarden kubewarden-controller kubewarden/kubewarden-controller --set image.repository=ghcr.io/jvanz/kubewarden-controller --set image.tag=controller-readiness-probe
Error: INSTALLATION FAILED: failed post-install: warning: Hook post-install kubewarden-controller/templates/policyserver-default.yaml failed: Internal error occurred: failed calling webhook "mpolicyserver.kb.io": failed to call webhook: Post "https://kubewarden-controller-webhook-service.kubewarden.svc:443/mutate-policies-kubewarden-io-v1alpha2-policyserver?timeout=10s": context deadline exceeded
```

Let me know if you want/need any further information.

2022-02-03 12:29 UTC, jvanz commented
Nice cert manager discussion with similar issues: https://github.com/cert-manager/cert-manager/issues/2319

2022-02-10 21:20 UTC, jvanz commented
So, considering this comment 110. The issue which is holding this PR does not exist anymore. However, the PR does not fix the issue which it originally would to fix. It turns out to be an enhancement now. 

Should we merge it anyway?

2022-02-11 09:21 UTC, ereslibre requested changes
> Should we merge it anyway?

I have been looking at the controller-runtime code (referenced by the scaffold generated by kubebuilder). I think the change you propose seems sound at a first glance (keep reading). The implementation will just try to reach the Webhook port opening a `tcp` socket and checking whether it can be opened.

I didn't check about Go internals but in theory it should also be possible that the socket can open a connection, but the HTTP server is not yet ready to answer to requests. Again, this window is probably small (if it exists at all with the Go's standard library behavior). This would be a false positive if can happen.

Note that I'm being extremely picky because this is in theory fixing a race condition, and in such a situation, I think even if we merge this, there is probably another race condition waiting. I don't know if it is negligible in comparison to the current situation.

I also think that given this is not strictly fixing an issue we can reproduce and confirm is the fix for said issue we should not include it.

If we have good reasons that this should be included, I would consider opening this change against the `kubebuilder` project as well, so the generated scaffolds are more sound.

2022-02-11 16:43 UTC, jvanz commented
Okay. I understand. I do not see reason to keep this open. The fix is not actually a fix. So, I'm closing it.

2022-02-11 16:43 UTC, closed without merging