Upgrade artifact upload/download to v4
kubewarden/kubewarden-controller pull request #602
Opened 2023-12-21 18:13 UTC by kravciak

## Description

Fix #XXX

## Test

To test this pull request, you can run the following commands:

## Additional Information

### Tradeoff

### Potential improvement

2023-12-22 09:51 UTC, viccuad requested changes
Are you sure this is going to work?
From https://github.com/kubewarden/audit-scanner/pull/162/files, I realized that each sbom needed a suffix per arch, and I needed to use `pattern: sbom*` and  `merge-multiple: true` to be able to download all of them at once.

Could you test this in your fork with a tag, to see a successful release run? (you may need to create a previous tag, and an empty draft release so the job can succeed).

2023-12-22 16:42 UTC, kravciak commented
I got this far https://github.com/kravciak/kubewarden-controller/actions/runs/7300731924/job/19896296077 - I fight with release drafts, tags, ...
Is this enough? Otherwise I could use some help with release steps.

2024-01-02 10:18 UTC, viccuad approved these changes
Thanks! approving

2024-01-02 10:19 UTC, viccuad commented
@kravciak it seems that not all commits are signed with gpgp, can you please rebase?

2024-01-02 10:29 UTC, kravciak commented
> @kravciak it seems that not all commits are signed with gpgp, can you please rebase?

Eh, changed the commit and forgot to sign new one - fixed, thanks.

2024-01-02 14:08 UTC, merged