fix(test): rewrite webhooks tests as unit tests.
kubewarden/kubewarden-controller pull request #646
Opened 2024-02-22 14:04 UTC by jvanz

## Description

The webhook_suite_test.go originally test webhook validations with integrations test on Ginkgo. Which is slow because it setup a whole test environment to simulate Kubernetes cluster. This commit changes that rewriting the test as unit tests calling the validation function directly.

Fix #579

2024-02-23 09:27 UTC, fabriziosestito requested changes
The table testing looks great and IMHO it is much better than relying on etcd to test validations. 
However, I see other improvements that could be made.
Here, we are not testing the webhooks but the pure validation functions, which are common to every struct that implements the `Policy` interface.
It's a bit weird that the admission policy uses those functions from the cluster admission policy type file so that we could have two simple changes to clean up a little bit:
1. move the common validations functions to a separate file (i.e. `policy_validation.go`) and rename the `clusteradmission_webhook_test.go` file accordingly.
2. create `clusteradmissionpolicy_webhook_test` and `admissionpolicy_webhook_test` where we test that the wire-up is ok by testing `Default()`, `ValidateCreate`, and `ValidateUpdate` with simple valid data (don't need to re-test that the validation works, just that the methods are doing what expected). This overlaps a bit with the validation testing but it gives us the confidence that the methods are working correctly (for instance, they are updating the policy struct correctly or returning the expected default type).

2024-02-23 15:06 UTC, fabriziosestito commented on pkg/apis/policies/v1/policy_test_utils.go
> +/*
we should rename this to something with the `_test` suffix or these functions will be included in the final binary. (e.g. `utils_test.go`)

2024-02-23 15:06 UTC, fabriziosestito approved these changes
LGTM
:shipit: once the utils file is renamed

2024-02-26 09:58 UTC, flavio commented
@jvanz I think you can merge this PR after you have rebased it against `main`

2024-02-26 12:46 UTC, merged