chore: ade codecov configuration
kubewarden/kubewarden-controller pull request #675
Opened 2024-03-12 10:14 UTC by fabriziosestito

2024-03-12 13:02 UTC, jvanz requested changes
The codecov file seems fine to me. But I would like to move the crds changes in a dedicated commit and remove them from this PR and  open another one for them.

2024-03-12 13:04 UTC, fabriziosestito commented
> The codecov file seems fine to me. But I would like to move the crds changes in a dedicated commit and remove them from this PR and open another one for them.

@jvanz woops sorry I didn't notice that

2024-03-12 13:25 UTC, jvanz reviewed
Ops, this PR is not under review yet. Sorry. hehe

2024-03-12 14:47 UTC, viccuad approved these changes
LGTM

2024-03-12 17:02 UTC, jvanz approved these changes
LGTM

2024-03-13 08:32 UTC, flavio approved these changes
Go ahead and merge it :rocket:

2024-03-13 12:39 UTC, jvanz commented
I've just use github to rebase this PR on top of the latest main.

2024-03-13 13:56 UTC, merged