wip refactor cert
kubewarden/kubewarden-controller pull request #777
Opened 2024-06-20 16:44 UTC by fabriziosestito

## Description
Fix: #775

2024-06-24 08:17 UTC, flavio requested changes
I think we should address some naming confusion about Policy Server CA, see my notes.

Overall LGTM

2024-06-24 08:17 UTC, flavio commented on controllers/utils_test.go
> +func getTestPolicyServerCASecret() (*corev1.Secret, error) {
This is retrieving the Root CA created by our controller. I suggest to rename this helper function to reflect that.

Maybe something like `getInternalRootCASecret` ?

2024-06-24 08:17 UTC, flavio commented on internal/pkg/admission/policy-server-ca-secret.go
> +func (r *Reconciler) fetchOrInitializePolicyServerCASecret(ctx context.Context, policyServer *policiesv1.PolicyServer, caSecret *corev1.Secret) error {
Again, there's a bit of naming confusion here we inherited from the past.

This method creates the certificate used by a specific Policy Server instance, there's no CA associated with a Policy Server

2024-06-24 08:17 UTC, flavio commented on internal/pkg/admission/policy-server-ca-secret.go
> +func (r *Reconciler) fetchOrInitializePolicyServerCARootSecret(ctx context.Context, policyServer *policiesv1.PolicyServer) (*corev1.Secret, error) {
Same here, the naming is confusing since no CA is stored inside of the `Secret` that is returned

2024-06-24 08:17 UTC, flavio commented on internal/pkg/admission/policy-server-ca-secret.go
> +func updateCASecret(policyServerSecret *corev1.Secret) error {
This function is always generating the CA, it doesn't look into the contents of the secret that is passed as parameter.

Why don't we change the signature of the function to be something like that?

```golang
func createInternalCASecret() (policyServerSecret *corev1.Secret, error)
```

2024-06-24 08:17 UTC, flavio commented on internal/pkg/admission/policy-server-ca-secret.go
Maybe something for later, but I would also rename this file since it can mislead into thinking each Policy Server has a dedicated CA

2024-06-24 08:17 UTC, flavio commented on internal/pkg/certs/ca.go
> +func GenerateCA() ([]byte, *rsa.PrivateKey, error) {
Can you add some inline documentation explaining what is returned by the function?

2024-06-24 08:17 UTC, flavio commented on internal/pkg/certs/cert.go
> +	privateKey, err := rsa.GenerateKey(rand.Reader, 4096)
Maybe we could create a constant defining the size of the key? This would be used to create the internal CA and the Policy Server certs.

2024-06-24 08:17 UTC, flavio commented on internal/pkg/certs/cert.go
>  func GenerateCert(ca []byte,
Please add some inline docs

2024-06-24 12:50 UTC, fabriziosestito commented
@flavio I've addressed the comments in https://github.com/kubewarden/kubewarden-controller/pull/777/commits/c3cbdf4e9759e6e0fa2900d2343bcde0865cfe43. 

I tracked all the naming-related comments in: https://github.com/kubewarden/kubewarden-controller/issues/782

2024-06-24 20:41 UTC, jvanz approved these changes

2024-06-25 07:40 UTC, fabriziosestito commented
Blocked: waiting for 1.14 release

2024-06-26 08:44 UTC, flavio approved these changes
Approving, the naming changes I've suggested are going to be done inside of future PRs

2024-06-26 08:55 UTC, merged